spring:
  application:
    name: gestion-bu
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
