spring:
  application:
    name: uadb-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      enabled: true
      uri: http://config-service:8888
      import-check:
        enabled: false
